name: DEST INSTITUTE
favicon: null
layout_spectrum: 0.4965387841220945
typography_spectrum: 0.3352666136343032
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.45613630791194737
  lightness: 0.974914305144921
  saturation: 0.4619303757790476
  rhythmicContrast: 0.1063136865850538
purpose: []
