name: DEST INSTITUTE
favicon: null
layout_spectrum: 0
typography_spectrum: 0.18502
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dbe5ee'
    - '#c3d3db'
    - '#94a4ab'
    - '#6b858f'
    - '#57727c'
  brandStrength: 0
  lightness: 0.974914305144921
  saturation: 0.0625
  rhythmicContrast: 0.1063136865850538
purpose: []
